### PR TITLE
Add personas

### PR DESCRIPTION
**Pull request by greatbacon**
This PR introduces the Persona table and interjects it as a interface between an Account (which has a 1:1 representational relationship with a human; and a persona which covers the different contexts we interact with communities under.

Currently there is no way to make a new persona, delete a persona, or switch between multiple personas, so it is functionally similar to the pre-persona account behavior. 

- [ ] There's still a bug where when switching between accounts that don't share communities the member list doesn't update properly.

### CODE REVIEW

**Review by ryanatkn — APPROVED** [review]
Nice this looks great. What's the thinking behind the `active_persona` in the session? I'd expect that to be temporary state in the client, and still load everything by account.

**Comment by greatbacon** [comment]
> Nice this looks great. What's the thinking behind the `active_persona` in the session? I'd expect that to be temporary state in the client, and still load everything by account.

That was a shortcut in response to swapping the Persona with Account as the main relation for communities & posts. I suppose we could load all communities for all personas on the backend and pass it to the client. I guess I assumed the `active_persona` was the temporary state in the client. If that's not the right solution what should we do instead?

**Comment by greatbacon** [comment]
> > I suppose we could load all communities for all personas on the backend and pass it to the client.
> 
> That sounds good to me, thick session payload. A future optimization could let clients specify only a subset of personas/communities, but for now the full take of (meta)data makes sense to send on load.

Cool; in that case is session still an okay place for storing the "active" persona to render from the thick payload? Or is there a better place we could/should be storing that for now?

**Comment by ryanatkn** [comment]
I think the right spot with current patterns is `src/ui/ui.ts` alongside state like `selected_community_id`. We can assume that there's one persona per community for now.

**Comment by greatbacon** [comment]
Okay, I'm going to go ahead and merge what I have, and open another PR for managing any frontend state & rendering work!

**Pull request merged**
