### PR TITLE
Set up an initial actions file

### PR DESCRIPTION
**Pull request by greatbacon**
Adds a `build` file for github actions

### CODE REVIEW

**Review by ryanatkn — APPROVED** [review]
Looks good!

**Comment by ryanatkn** [comment]
We also have `gro check` that is an alias for:

- `npm test`
- typechecking with TypeScript
- format checking with Prettier
- codegen is fresh (if the project uses this feature)

**Comment by greatbacon** [comment]
> We also have `gro check` that is an alias for:
> 
> * `npm test`
> * typechecking with TypeScript
> * format checking with Prettier
> * codegen is fresh (if the project uses this feature)
> 
> example: https://github.com/feltcoop/gro/blob/main/.github/workflows/nodejs.yml#L29

Good to know! I ran into a snag trying to install gro, so I'm gonna do stuff with that in a follow up PR

**Comment by ryanatkn** [comment]
Was just thinking of that, see this example: 

https://github.com/feltcoop/felt-mockup/blob/main/.github/workflows/nodejs.yml#L44

**Comment by ryanatkn** [comment]
There's also `npm ci` but I'm ignorant here. I've looked at other projects and I see both `npm i` and `npm ci` used, so maybe it doesn't matter? But the docs seem to indicate it'll be faster. https://docs.npmjs.com/cli/v7/commands/npm-ci

**Pull request merged**
